#!/usr/bin/env python3
"""Reconstruct and orient the GENDEP target marker set.

Purpose
-------
Combine the supplied rsID list and aggregate genotype frequencies with fixed
Ensembl GRCh37, GenoPred and PRS-CS references. The command produces the final
orientation table and PRS-CS-compatible scoring ceiling without reading the
remission outcome.

Inputs
------
A project YAML configuration, an rsID list generated by ``genotype_audit.R``
and the matching aggregate genotype-frequency table.

Outputs
-------
Reference reconstruction, source classification, GenoPred overlap, final
oriented markers, PRS-CS intersection tables, summaries and checksums.

Usage
-----
gendep reconstruct-target --config config/project.yml
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
SRC = REPOSITORY_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from gendep.genotype.common import read_variant_ids, sha256, write_tsv  # noqa: E402
from gendep.genotype.orientation import (  # noqa: E402
    intersect_prscs,
    marker_to_dict,
    orient_markers,
    pearson_code2_vs_eur_major,
    read_genotype_frequencies,
)
from gendep.genotype.reference import (  # noqa: E402
    match_genopred_reference,
    scan_ensembl_vcfs,
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the target-reconstruction command."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="Project configuration YAML.")
    parser.add_argument(
        "--expected",
        default=str(REPOSITORY_ROOT / "config" / "expected_results.yml"),
        help="Optional expected-results YAML used for regression checks.",
    )
    parser.add_argument("--variant-list", help="Override the configured source rsID list.")
    parser.add_argument("--frequency-table", help="Override the configured frequency table.")
    parser.add_argument("--output-dir", help="Override the configured genotype work directory.")
    parser.add_argument(
        "--skip-ensembl",
        action="store_true",
        help="Skip Ensembl reconstruction and classify source variants as unknown.",
    )
    return parser.parse_args()


def resolve_path(value: str, project_root: Path) -> Path:
    """Resolve path from configuration and validated paths."""
    path = Path(value).expanduser()
    return path if path.is_absolute() else project_root / path


def resolve_pattern(value: str, project_root: Path) -> str:
    """Resolve pattern from configuration and validated paths."""
    path = Path(value).expanduser()
    return str(path if path.is_absolute() else project_root / path)


def require_config(config: dict, *keys: str):
    """Require config and raise a clear error when absent."""
    value = config
    for key in keys:
        if not isinstance(value, dict) or key not in value:
            raise KeyError("Missing configuration value: " + ".".join(keys))
        value = value[key]
    return value


def metric_rows(counter: Counter[str] | dict[str, object]):
    """Convert reconstruction summary metrics to release-safe table rows."""
    for key in sorted(counter):
        yield {"metric": key, "value": counter[key]}


def validate_expected(observed: dict[str, int | float], expected_path: Path) -> list[dict[str, object]]:
    """Validate expected against the fixed project invariants."""
    if not expected_path.is_file():
        return []
    expected = yaml.safe_load(expected_path.read_text(encoding="utf-8")) or {}
    variants = expected.get("variants", {})
    expected_map = {
        "supplied_variants": variants.get("supplied"),
        "reconstructed_autosomal_snvs": variants.get("reconstructed_autosomal_snvs"),
        "excluded_non_snv": variants.get("excluded_non_snv"),
        "unresolved_rsids": variants.get("unresolved_rsids"),
        "official_genopred_overlap": variants.get("official_genopred_overlap"),
        "final_oriented_target": variants.get("final_oriented_target"),
        "prscs_compatible": variants.get("prscs_compatible"),
        "same_order": variants.get("prscs_same_order"),
        "swapped_order": variants.get("prscs_swapped_order"),
        "absent_from_prscs": variants.get("absent_from_prscs"),
        "orientation_sample_major_agreement": variants.get("orientation_sample_major_agreement"),
        "orientation_sample_frequency_flip": variants.get("orientation_sample_frequency_flip"),
        "orientation_sample_frequency_tie": variants.get("orientation_sample_frequency_tie"),
        "excluded_eur_frequency_ties": variants.get("excluded_eur_frequency_ties"),
    }
    rows: list[dict[str, object]] = []
    failures: list[str] = []
    for metric, expected_value in expected_map.items():
        if expected_value is None or metric not in observed:
            continue
        observed_value = observed[metric]
        passed = int(observed_value) == int(expected_value)
        rows.append(
            {
                "metric": metric,
                "expected": expected_value,
                "observed": observed_value,
                "pass": "TRUE" if passed else "FALSE",
            }
        )
        if not passed:
            failures.append(f"{metric}: expected {expected_value}, observed {observed_value}")

    expected_correlation = variants.get("orientation_correlation")
    if expected_correlation is not None and "orientation_correlation" in observed:
        tolerance = float(expected.get("tolerance", {}).get("absolute", 1e-12))
        difference = abs(float(observed["orientation_correlation"]) - float(expected_correlation))
        passed = difference <= tolerance
        rows.append(
            {
                "metric": "orientation_correlation",
                "expected": expected_correlation,
                "observed": observed["orientation_correlation"],
                "pass": "TRUE" if passed else "FALSE",
            }
        )
        if not passed:
            failures.append(
                "orientation_correlation: expected "
                f"{expected_correlation}, observed {observed['orientation_correlation']}"
            )
    if failures:
        raise RuntimeError("Reconstruction regression checks failed:\n" + "\n".join(failures))
    return rows


def main() -> None:
    """Reconstruct and orient the final target-marker table."""
    args = parse_args()
    config_path = Path(args.config).resolve()
    config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    project_root = resolve_path(config.get("project_root", "."), config_path.parent).resolve()

    controlled = require_config(config, "controlled_data")
    resources = require_config(config, "external_resources")
    outputs = config.get("outputs", {})

    variant_list = resolve_path(
        args.variant_list or controlled.get("genotype_variant_list", "work/genotype/source_variant_ids.txt"),
        project_root,
    )
    frequency_table = resolve_path(
        args.frequency_table
        or controlled.get("genotype_frequency_table", "work/genotype/source_genotype_frequencies.tsv.gz"),
        project_root,
    )
    output_dir = resolve_path(
        args.output_dir or outputs.get("genotype_reconstruction", "work/genotype/reconstruction"),
        project_root,
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    if not variant_list.is_file():
        raise FileNotFoundError(f"Source variant list not found: {variant_list}")
    if not frequency_table.is_file():
        raise FileNotFoundError(f"Genotype frequency table not found: {frequency_table}")

    variant_ids = read_variant_ids(variant_list)
    frequencies = read_genotype_frequencies(frequency_table)
    if set(variant_ids) != set(frequencies):
        missing = sorted(set(variant_ids).difference(frequencies))
        extra = sorted(set(frequencies).difference(variant_ids))
        raise ValueError(
            "Variant list and frequency table disagree. "
            f"Missing frequencies={len(missing)}, unexpected frequencies={len(extra)}"
        )

    chromosomes = [int(value) for value in config.get("genotype", {}).get("chromosomes", range(1, 23))]
    if not chromosomes or any(value not in range(1, 23) for value in chromosomes):
        raise ValueError("Configured genotype chromosomes must be integers from 1 to 22")

    if args.skip_ensembl:
        ensembl_records = []
        source_classification = {variant_id: "unknown" for variant_id in variant_ids}
        ensembl_counts = Counter(requested_unique_rsids=len(variant_ids))
    else:
        ensembl_pattern = resolve_pattern(require_config(resources, "ensembl_vcf_pattern"), project_root)
        ensembl_records, source_classification, ensembl_counts = scan_ensembl_vcfs(
            variant_ids, ensembl_pattern, chromosomes=chromosomes
        )

    pvar_pattern = resolve_pattern(require_config(resources, "genopred_pvar_pattern"), project_root)
    afreq_pattern = resolve_pattern(require_config(resources, "genopred_eur_afreq_pattern"), project_root)
    genopred_records, genopred_exclusions, genopred_counts = match_genopred_reference(
        variant_ids, pvar_pattern, afreq_pattern, chromosomes=chromosomes
    )

    retained, excluded_ties, orientation_counts = orient_markers(
        genopred_records, frequencies, source_classification
    )
    correlation = pearson_code2_vs_eur_major(retained + excluded_ties)

    snpinfo_path = resolve_path(require_config(resources, "prscs_snpinfo"), project_root)
    compatible, prscs_excluded, prscs_counts = intersect_prscs(retained, snpinfo_path)

    ensembl_fields = [
        "chromosome",
        "position",
        "variant_id",
        "ref",
        "alt",
        "variant_class",
        "is_multiallelic",
        "is_ambiguous",
    ]
    write_tsv(
        output_dir / "ensembl_reconstruction.tsv.gz",
        ensembl_fields,
        (asdict(record) for record in ensembl_records),
    )
    write_tsv(
        output_dir / "source_variant_classification.tsv.gz",
        ["SNP", "classification"],
        ({"SNP": variant_id, "classification": source_classification[variant_id]} for variant_id in variant_ids),
    )

    genopred_fields = [
        "SNP",
        "GENOPRED_CHR",
        "GENOPRED_BP",
        "GENOPRED_REF",
        "GENOPRED_ALT",
        "EUR_ALT_FREQ",
        "EUR_OBS_CT",
        "ORIGINAL_CATEGORY",
    ]
    write_tsv(
        output_dir / "genopred_reference_matches.tsv.gz",
        genopred_fields,
        (
            {
                "SNP": record.variant_id,
                "GENOPRED_CHR": record.chromosome,
                "GENOPRED_BP": record.position,
                "GENOPRED_REF": record.ref,
                "GENOPRED_ALT": record.alt,
                "EUR_ALT_FREQ": format(record.eur_alt_freq, ".17g"),
                "EUR_OBS_CT": record.eur_obs_ct,
                "ORIGINAL_CATEGORY": source_classification.get(record.variant_id, "unknown"),
            }
            for record in genopred_records
        ),
    )
    write_tsv(
        output_dir / "genopred_reference_exclusions.tsv.gz",
        ["SNP", "reason"],
        ({"SNP": variant_id, "reason": reason} for variant_id, reason in sorted(genopred_exclusions.items())),
    )

    marker_fields = list(marker_to_dict((retained + excluded_ties)[0]).keys())
    write_tsv(
        output_dir / "target_orientation_all.tsv.gz",
        marker_fields,
        (marker_to_dict(marker) for marker in retained + excluded_ties),
    )
    write_tsv(
        output_dir / "final_target_markers.tsv.gz",
        marker_fields,
        (marker_to_dict(marker) for marker in retained),
    )
    write_tsv(
        output_dir / "excluded_eur_frequency_ties.tsv",
        marker_fields,
        (marker_to_dict(marker) for marker in excluded_ties),
    )

    prscs_fields = list(compatible[0].keys()) if compatible else marker_fields
    write_tsv(output_dir / "prscs_compatible_markers.tsv.gz", prscs_fields, compatible)
    excluded_fields = sorted({key for row in prscs_excluded for key in row}) or marker_fields
    write_tsv(output_dir / "prscs_excluded_markers.tsv.gz", excluded_fields, prscs_excluded)

    classification_counts = Counter(source_classification.values())
    summary = {
        "supplied_variants": len(variant_ids),
        "reconstructed_autosomal_snvs": classification_counts["reconstructed_autosomal_snv"],
        "excluded_non_snv": classification_counts["excluded_non_snv"],
        "unresolved_rsids": classification_counts["unresolved_rsid"],
        "official_genopred_overlap": len(genopred_records),
        "final_oriented_target": len(retained),
        "excluded_eur_frequency_ties": len(excluded_ties),
        "prscs_compatible": len(compatible),
        "same_order": prscs_counts["same_order"],
        "swapped_order": prscs_counts["swapped_order"],
        "strand_complement": prscs_counts["strand_complement"],
        "strand_complement_swapped": prscs_counts["strand_complement_swapped"],
        "absent_from_prscs": prscs_counts["absent_from_prscs"],
        "orientation_sample_major_agreement": orientation_counts[
            "retain_sample_and_eur_major_agree"
        ],
        "orientation_sample_frequency_flip": orientation_counts[
            "retain_eur_major_sample_flip_near_half"
        ],
        "orientation_sample_frequency_tie": orientation_counts[
            "retain_eur_major_sample_tie"
        ],
        "orientation_correlation": correlation,
    }
    write_tsv(output_dir / "reconstruction_summary.tsv", ["metric", "value"], metric_rows(summary))
    write_tsv(output_dir / "ensembl_summary.tsv", ["metric", "value"], metric_rows(ensembl_counts))
    write_tsv(output_dir / "genopred_summary.tsv", ["metric", "value"], metric_rows(genopred_counts))
    write_tsv(output_dir / "orientation_summary.tsv", ["metric", "value"], metric_rows(orientation_counts))
    write_tsv(output_dir / "prscs_summary.tsv", ["metric", "value"], metric_rows(prscs_counts))

    chromosome_rows = []
    by_chromosome = defaultdict(Counter)
    for marker in retained + excluded_ties:
        by_chromosome[marker.GENOPRED_CHR]["matched_variants"] += 1
        if marker.KEEP_FOR_TARGET:
            by_chromosome[marker.GENOPRED_CHR]["retained_variants"] += 1
        else:
            by_chromosome[marker.GENOPRED_CHR]["excluded_eur_frequency_ties"] += 1
    for row in compatible:
        by_chromosome[str(row["GENOPRED_CHR"])]["prscs_compatible"] += 1
    for chromosome in map(str, chromosomes):
        values = by_chromosome[chromosome]
        chromosome_rows.append(
            {
                "chromosome": chromosome,
                "matched_variants": values["matched_variants"],
                "retained_variants": values["retained_variants"],
                "excluded_eur_frequency_ties": values["excluded_eur_frequency_ties"],
                "prscs_compatible": values["prscs_compatible"],
            }
        )
    write_tsv(
        output_dir / "target_markers_by_chromosome.tsv",
        [
            "chromosome",
            "matched_variants",
            "retained_variants",
            "excluded_eur_frequency_ties",
            "prscs_compatible",
        ],
        chromosome_rows,
    )

    regression_rows = validate_expected(summary, Path(args.expected)) if args.expected else []
    if regression_rows:
        write_tsv(
            output_dir / "reconstruction_regression_validation.tsv",
            ["metric", "expected", "observed", "pass"],
            regression_rows,
        )

    output_files = sorted(path for path in output_dir.iterdir() if path.is_file())
    manifest = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "config": str(config_path),
        "variant_list": str(variant_list),
        "frequency_table": str(frequency_table),
        "resources": {
            "ensembl_vcf_pattern": ensembl_pattern if not args.skip_ensembl else None,
            "genopred_pvar_pattern": pvar_pattern,
            "genopred_eur_afreq_pattern": afreq_pattern,
            "prscs_snpinfo": str(snpinfo_path),
        },
        "summary": summary,
        "outputs": {path.name: sha256(path) for path in output_files},
    }
    (output_dir / "reconstruction_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print("Target reconstruction completed successfully.")
    for metric, value in summary.items():
        if isinstance(value, float):
            print(f"{metric}: {value:.12g}")
        else:
            print(f"{metric}: {value}")
    print(f"Outputs: {output_dir}")


if __name__ == "__main__":
    main()
